### ISSUE TITLE
LeakGAN_G

### ISSUE THREAD

**Issue by saeedEnte** [williamSYSU/TextGAN-PyTorch#17]
This class doesn't have any function `init_param()`. I think it can't inherit from `LSTMGenerator` as its initialization gets other params

**Comment by williamSYSU** [comment]
You're right. The `LeakGAN_G` can't inherit the `init_param()` from `LSTMGenerator`. So the initialization function of `LeakGAN_G` should be implemented in its own class.

**Comment by saeedEnte** [comment]
I have just copy the `init_param` from other functions and now everything is fine. TNX

**Comment by williamSYSU** [comment]
I have fixed that mistake and updated the codes. :)
