### ISSUE TITLE
what is the output

### ISSUE THREAD

**Issue by saharjandaghy** [williamSYSU/TextGAN-PyTorch#19]
what is the output of program exactly? my output is some numbers?  How can I convert numbers to sentences?

**Comment by williamSYSU** [comment]
The reason why the generated samples of program are some numbers is because you ran the program with synthetic data. You need to change the parameters (in `config.py`) as `if_real_data=True` and `dataset='image_coco'` (or others real datasets).

**Comment by julfr** [comment]
> The reason why the generated samples of program are some numbers is because you ran the program with synthetic data. You need to change the parameters (in `config.py`) as `if_real_data=True` and `dataset='image_coco'` (or others real datasets).

I changed `if_real_data=True` and chose `dataset='emnlp_news' ` in `config.py`, but still see, that it uses 'oracle'. What could be a problem?
