### ISSUE TITLE
Is there an easy way to view the generator's output samples during training?

### ISSUE THREAD

**Issue by ishalyminov** [williamSYSU/TextGAN-PyTorch#2]

**Comment by williamSYSU** [comment]
The code would automatically save the state dict of models and a batch-size of generator's samples in <code>./save/\*\*/models</code> and <code>./save/\*\*/samples</code> per log step, where <code>\*\*</code> depends on your hyper-parameters. Please refer to <code>instructor.py</code> for the code. By the way, you remind me to continue to improve <code>README.md</code>.

**Comment by ishalyminov** [comment]
Thanks a lot!
Your implementation seems to be really efficient in terms of the training progress, so I'm just curious what it's actually learning :)
I'll try to contribute as well once I'm familiar enough with the code!
