### ISSUE TITLE
Porting attention version of RMC

### ISSUE THREAD

**Issue by lethaiq** [williamSYSU/TextGAN-PyTorch#23]
Do you have any plans to port the attention RMC models over? Even though RelGAN_D with rmc attention is not working well with the current GAN settings (claimed from RelGAN paper author), I think it is still a good idea to port it over. 

I am sure can help you debug and check it after it is ported.

**Comment by williamSYSU** [comment]
Sorry, currently I have no plan to port the attention RMC models over, as the vanilla RMC work well. Yet it would be great if you could port it over and create a pull request. :)
