### ISSUE TITLE
How to deal with Out of Vocabulary tokens?

### ISSUE THREAD

**Issue by lethaiq** [williamSYSU/TextGAN-PyTorch#25]
@williamSYSU I have a small question. I am trying to understand how you handle Out of vocabulary tokens, since we can  a max cap on the vocabulary size if we deal with another dataset. I can see that in the current code, there is only 2 special tokens: start_token and padding_token, and the two datasets COO image and EMNLP both has a very limited size of vocabulary (around 6K) so you are getting all the unique tokens in the main.py file. How should we handle a dataset with larger vocabulary base?

**Comment by williamSYSU** [comment]
I am not sure if I fully understand your question. There are two vocabularies for training data and test data. The vocabulary of training data is initialized (or loaded) at the begin of the program (as in `main.py`) based on the given training data file. The two vocabularies share common words, while the vocabulary of test data may have additional words that are not in the training data. The training data and the test data are loaded by  `load_dict()` and `load_test_dict()` in `utils/text_process.py`, respectively. 
That is, before training the model, the vocabularies of training data and test data have included all tokens we need. Thus, there should not be an Out of Vocabulary Tokens error while running the program.

**Comment by lethaiq** [comment]
@williamSYSU thanks for the response it took me a while to figure it out that in your code we do not have constraints on the vocabulary size. We can add this option to the current code base, it might be helpful!
