### ISSUE TITLE
Train LeakGAN with a custom dataset?

### ISSUE THREAD

**Issue by ishalyminov** [williamSYSU/TextGAN-PyTorch#5]
Hi,

Could you please advise what's the way to train LeakGAN on a custom, real dataset?

Currently, I'm at the step of providing the Oracle with real samples from my dataset. I see they are already vectorized - which vocabulary is it done with?

I'll probably have more questions down the road, so it would be great if you could bear with me :)

**Comment by williamSYSU** [comment]
I have added the LeakGAN instructor `leakgan_instructor.py` in `instructor/real_data', please refer to it.

For a custom dataset, the steps should be as follows:

1. Preprocess dataset files, one sentence per line, ending with '\n'. Put them into `dataset` folder, training data should be placed in the root of `dataset` and testing data should be placed in the `testdata`.

2. Please refer to the function `init_dict()` in `utils/text_process.py`, similarly add the code to load your custom dataset files. (This function will automatically initialing dictionary based on `dataset` args in the future.)

3. Now you can design your own Instructor. The main differences of instructors between oracle data and real data are:

    - `self.oracle_data` should load training data (`config.train_data`) and add a `self.test_data` loading testing data (`config.test_data`).

    - Add BLEU metrics.

    - The positive samples for discriminator should be `self.oracle_data.target' now.

    - Remove the evaluation process of discriminator since there is no validation data.

    - Change the way of saving generator's samples. Before changing `write_tensor` to `write_tokens`, use `tensor_to_tokens()` to transform Tensor to word tokens.

See 'instructor/real_data/leakgan_instructor.py' for more details.

Please don't worry that these questions will bother me. These also help me to improve my code.

**Comment by ishalyminov** [comment]
Perfect, thanks a lot! 🙏
