### ISSUE TITLE
Runtime Error when running LeakGAN

### ISSUE THREAD

**Issue by Vaseekaran-V** [williamSYSU/TextGAN-PyTorch#59]
Hi. So I uploaded the code in Kaggle to use the GPU, and while running the LeakGAN, I came across this error:

>>>Creating Oracle...
NLL_Oracle Groud Truth: 5.6707
Creating Oracle 0...
Oracle 0 Groud Truth: 5.9815
Creating Oracle 1...
Oracle 1 Groud Truth: 5.8890
>>> Interleaved Round 0...
Starting Discriminator Training...
[MLE-DIS] d_step 0: d_loss = 0.0152, train_acc = 0.9962, eval_acc = 0.9922,
[MLE-DIS] d_step 1: d_loss = 0.0022, train_acc = 0.9999, eval_acc = 0.9941,
[MLE-DIS] d_step 2: d_loss = 0.0011, train_acc = 0.9999, eval_acc = 0.9961,
[MLE-DIS] d_step 3: d_loss = 0.0009, train_acc = 1.0000, eval_acc = 0.9951,
[MLE-DIS] d_step 4: d_loss = 0.0005, train_acc = 1.0000, eval_acc = 0.9961,
Save pre-trained discriminator: pretrain/oracle_data/dis_pretrain_leakgan_vanilla_sl20_sn10000.pt
Starting Generator MLE Training...
Traceback (most recent call last):
  File "main.py", line 169, in <module>
    inst._run()
  File "/kaggle/working/textgan-pytorch/instructor/oracle_data/leakgan_instructor.py", line 56, in _run
    self.pretrain_generator(cfg.MLE_train_epoch)
  File "/kaggle/working/textgan-pytorch/instructor/oracle_data/leakgan_instructor.py", line 106, in pretrain_generator
    self.optimize_multi(self.gen_opt, [mana_loss, work_loss])
  File "/kaggle/working/textgan-pytorch/instructor/oracle_data/instructor.py", line 147, in optimize_multi
    loss.backward(retain_graph=True if i < len(opts) - 1 else False)
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [32, 1720]], which is output 0 of TBackward, is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Is there any fix for this? Or is it causing an error because I tried to run the code in the Kaggle environment?

**Comment by Vaseekaran-V** [comment]
This issue was fixed by changing the torch version to 1.4.0.

**Comment by julfr** [comment]
> This issue was fixed by changing the torch version to 1.4.0.

I have the same issue, although my torch version is 1.10.2
