### ISSUE TITLE
ImportError: No module named torch

### ISSUE THREAD

**Issue by grmarco** [williamSYSU/TextGAN-PyTorch#8]
Hello, I have the same issue as https://github.com/williamSYSU/TextGAN-PyTorch/issues/6 but I don't understand the solution. 
Thanks in advance for your time

**Comment by williamSYSU** [comment]
You may run program in a virtual environment, so you need to change the `executable = 'python'` in `run_[run_model].py` to your own environment python interpreter path.

**Comment by grmarco** [comment]
It works. Thank you very much for help me to solve this problem and, of course, for your extraordinary work with TextGAN.
